### ISSUE TITLE
Outdated installation requirements

### ISSUE THREAD

**Issue by mschnepf** [MatterMiners/lapis#18]
lapis does not work with the required version of usim (release v0.1.0). It seams that the current version of usim (commit 0a8a9b6c98b28ead9a17399a504989766ae12037) is required.

**Comment by maxfischer2781** [comment]
``usim`` has been released as ``0.2.0``. Please check whether that fixes the issue.

**Comment by eileen-kuehn** [comment]
I will provide a proper configuration for lapis asap :)

**Comment by mschnepf** [comment]
It works now :+1:
