### ISSUE TITLE
Finish output in Simulator is not reached

### ISSUE THREAD

**Issue by tfesenbecker** [MatterMiners/lapis#38]
According to line https://github.com/MatterMiners/lapis/blob/b16342593166fa4475bdb3ac366fb5bf08b74fdd/lapis/simulator.py#L67 there should be a printed output that the simulation is finished. This does not appear to be reached using usim version 0.3.0.

**Comment by eileen-kuehn** [comment]
Could you please install the recent version of lapis from PyPI and tell us, if the simulation still does not finish? 

Otherwise we need some more data for proper reproduction. Please send us python version and version of all installed packages in your venv.

**Comment by tfesenbecker** [comment]
No, it doesn't.
Python version: 3.6.8
Other packages version: 
![Screenshot at 2019-10-25 13-45-29](https://user-images.githubusercontent.com/50665055/67568897-c0b22480-f72d-11e9-9679-786bd6f8fb59.png)

**Comment by eileen-kuehn** [comment]
Please also update usim and try with version 0.4.0. You are still on 0.3.0.

**Comment by maxfischer2781** [comment]
This appears to be a combination of infinite, non-volatile activities and MaineKuehn/usim#66.
