### ISSUE TITLE
Resource allocation later than the following scheduling cycle?

### ISSUE THREAD

**Issue by tfesenbecker** [MatterMiners/lapis#39]
Using the input files below I observed that during the first scheduling two jobs are allocated to the same 1-core drone. The awaitable in line https://github.com/MatterMiners/lapis/blob/b16342593166fa4475bdb3ac366fb5bf08b74fdd/lapis/drone.py#L134 doesn't seem to be completed for one of the jobs allocated to the drone. Maybe this also leads to the missing output in #38 . 

```
RequestCpus RequestWalltime RequestMemory RequestDisk QDate RemoteWallClockTime 'Number of Allocated Processors' MemoryUsage DiskUsage_RAW RemoteSysCpu RemoteUserCpu
1 60 2000 6000000 1567169672 50.0 1 2867 41898 10.0 40.0
1 60 2000 6000000 1567155456 57.0 1 1207 45562 7.0 50.0
1 60 3500 8000000 1567132776 43.0 1 1683 1101910 3.0 40.0
```

```
TotalSlotCPUs   TotalSlotDisk           TotalSlotMemory Count
1             44624348.0              4000  2




```

**Comment by eileen-kuehn** [comment]
@maxfischer2781, could you please check the `await` from usim site. Could this be the issue we had with one of the very old versions of usim?

**Comment by maxfischer2781** [comment]
IIRC we had such an issue as a result of MaineKuehn/usim#34. That one should be part of ``usim`` 0.3.0 however.

@tfesenbecker, can you add some debug/prints to ``lapis.job.Job.run`` to see where it gets stuck?

**Comment by tfesenbecker** [comment]
The lines I inserted at the begging of` lapis.job.Job.run`, before the mentioned 
 https://github.com/MatterMiners/lapis/blob/b16342593166fa4475bdb3ac366fb5bf08b74fdd/lapis/drone.py#L134 , after this await and at the end of ` lapis.job.Job.run` are marked by 

> DEBUG

 at the beginning of the line. 
The resulting output is: 

> starting static environment
>  running until None
> Starting simulation at 0
> DEBUG: starting job <Job: 140527497602776> @ time 60
> {"time": "1970-01-01 01:01:00,198", "message": "job_status", "job_queue_time": {"<Job: 140527497602776>": 1567169672.0}, "job_waiting_time": {"<Job: 140527497602776>": 60}}
> DEBUG: awaiting completion of job <Job: 140527497602776> @ time 110.0
> DEBUG: starting job <Job: 140527497603672> @ time 60
> {"time": "1970-01-01 01:01:00,198", "message": "job_status", "job_queue_time": {"<Job: 140527497603672>": 1567132776.0}, "job_waiting_time": {"<Job: 140527497603672>": 60}}
> DEBUG: awaiting completion of job <Job: 140527497603672> @ time 103.0
> {"time": "1970-01-01 01:01:00,199", "message": "user_demand", "value": 1}
> {"time": "1970-01-01 01:01:00,199", "message": "cobald_status", "job_count": 0}
> {"time": "1970-01-01 01:01:00,199", "message": "cobald_status", "pool_configuration": "None", "pool_type": "pool", "pool": "<StaticPool: 140527495219184>", "allocation": 0.75, "utilisation": 0.5, "demand": 2, "supply": 2}
> {"time": "1970-01-01 01:01:00,199", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "allocation": 1.0, "utilisation": 1.0, "demand": 1, "supply": 1, "job_count": 0}
> {"time": "1970-01-01 01:01:00,199", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "allocation": 0.5, "utilisation": 0.0, "demand": 1, "supply": 1, "job_count": 0}
> {"time": "1970-01-01 01:01:00,199", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:00,199", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:00,199", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:00,199", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 1.0546875000017053e-05, "requested_ratio": 1.0}
> {"time": "1970-01-01 01:01:00,199", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 9.168989006935746e-07, "requested_ratio": 0.00013130443945086334}
> {"time": "1970-01-01 01:01:00,199", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.699951171875, "requested_ratio": 0.5}
> {"time": "1970-01-01 01:01:01,200", "message": "user_demand", "value": 1}
> {"time": "1970-01-01 01:01:01,200", "message": "cobald_status", "job_count": 1}
> {"time": "1970-01-01 01:01:01,200", "message": "cobald_status", "pool_configuration": "None", "pool_type": "pool", "pool": "<StaticPool: 140527495219184>", "allocation": 0.75, "utilisation": 0.5, "demand": 2, "supply": 2}
> {"time": "1970-01-01 01:01:01,200", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "allocation": 1.0, "utilisation": 1.0, "demand": 1, "supply": 1, "job_count": 0}
> {"time": "1970-01-01 01:01:01,200", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "allocation": 0.5, "utilisation": 0.0, "demand": 1, "supply": 1, "job_count": 1}
> {"time": "1970-01-01 01:01:01,200", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:01,200", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:01,200", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:01,200", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 1.0546875000017053e-05, "requested_ratio": 1.0}
> {"time": "1970-01-01 01:01:01,200", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 9.168989006935746e-07, "requested_ratio": 0.00013130443945086334}
> {"time": "1970-01-01 01:01:01,200", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.699951171875, "requested_ratio": 0.5}
> DEBUG: end of awaiting completion of job <Job: 140527497602776> @ time 160.0
> {"time": "1970-01-01 01:01:50,201", "message": "job_status", "job_wall_time": {"<Job: 140527497602776>": 50.0}}
> DEBUG: finish job <Job: 140527497602776> @ time 110.0, successful True
> {"time": "1970-01-01 01:01:50,201", "message": "user_demand", "value": 1}
> {"time": "1970-01-01 01:01:50,201", "message": "cobald_status", "job_count": 0}
> {"time": "1970-01-01 01:01:50,201", "message": "cobald_status", "pool_configuration": "None", "pool_type": "pool", "pool": "<StaticPool: 140527495219184>", "allocation": 1.0, "utilisation": 1.0, "demand": 2, "supply": 2}
> {"time": "1970-01-01 01:01:50,201", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "allocation": 1.0, "utilisation": 1.0, "demand": 1, "supply": 1, "job_count": 0}
> {"time": "1970-01-01 01:01:50,201", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "allocation": 1.0, "utilisation": 1.0, "demand": 1, "supply": 1, "job_count": 0}
> {"time": "1970-01-01 01:01:50,201", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:50,201", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:50,201", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:50,201", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:50,201", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:01:50,202", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.0, "requested_ratio": 0.0}
> DEBUG: starting job <Job: 140527497603336> @ time 120
> {"time": "1970-01-01 01:02:00,202", "message": "job_status", "job_queue_time": {"<Job: 140527497603336>": 1567155456.0}, "job_waiting_time": {"<Job: 140527497603336>": 120}}
> DEBUG: awaiting completion of job <Job: 140527497603336> @ time 177.0
> {"time": "1970-01-01 01:02:00,202", "message": "user_demand", "value": 0}
> {"time": "1970-01-01 01:02:00,202", "message": "cobald_status", "job_count": 1}
> {"time": "1970-01-01 01:02:00,202", "message": "cobald_status", "pool_configuration": "None", "pool_type": "pool", "pool": "<StaticPool: 140527495219184>", "allocation": 0.75, "utilisation": 0.5, "demand": 2, "supply": 2}
> {"time": "1970-01-01 01:02:00,203", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "allocation": 1.0, "utilisation": 1.0, "demand": 1, "supply": 1, "job_count": 0}
> {"time": "1970-01-01 01:02:00,203", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "allocation": 0.5, "utilisation": 0.0, "demand": 1, "supply": 1, "job_count": 1}
> {"time": "1970-01-01 01:02:00,203", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:02:00,203", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:02:00,203", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:02:00,203", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 7.692571271977755e-06, "requested_ratio": 1.0}
> {"time": "1970-01-01 01:02:00,203", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 9.970821450711043e-07, "requested_ratio": 0.00013130443945086334}
> {"time": "1970-01-01 01:02:00,203", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.294677734375, "requested_ratio": 0.5}
> DEBUG: end of awaiting completion of job <Job: 140527497603336> @ time 234.0
> {"time": "1970-01-01 01:02:57,203", "message": "job_status", "job_wall_time": {"<Job: 140527497603336>": 57.0}}
> DEBUG: finish job <Job: 140527497603336> @ time 177.0, successful True
> {"time": "1970-01-01 01:02:57,203", "message": "user_demand", "value": 0}
> {"time": "1970-01-01 01:02:57,204", "message": "cobald_status", "job_count": 0}
> {"time": "1970-01-01 01:02:57,204", "message": "cobald_status", "pool_configuration": "None", "pool_type": "pool", "pool": "<StaticPool: 140527495219184>", "allocation": 1.0, "utilisation": 1.0, "demand": 2, "supply": 2}
> {"time": "1970-01-01 01:02:57,204", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "allocation": 1.0, "utilisation": 1.0, "demand": 1, "supply": 1, "job_count": 0}
> {"time": "1970-01-01 01:02:57,204", "message": "cobald_status", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "allocation": 1.0, "utilisation": 1.0, "demand": 1, "supply": 1, "job_count": 0}
> {"time": "1970-01-01 01:02:57,204", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:02:57,204", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:02:57,204", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527495220360>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:02:57,204", "message": "resource_status", "resource_type": "cores", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:02:57,204", "message": "resource_status", "resource_type": "disk", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
> {"time": "1970-01-01 01:02:57,204", "message": "resource_status", "resource_type": "memory", "pool_configuration": "None", "pool_type": "drone", "pool": "<Drone: 140527494800552>", "used_ratio": 0.0, "requested_ratio": 0.0}
>

**Comment by eileen-kuehn** [comment]
Apparently, we currently have an issue with duration of `claim`ing resources, that we did not have to consider before.
We can now either fix the interval, in which the resources are claimed and/or improve the scheduler itself to support modes that a drone is either looked at in the next interval or already updated in terms of available resources.

We are working on it :)

**Comment by eileen-kuehn** [comment]
@tfesenbecker, please checkout the current version 0.3.0 available at PyPI. Hopefully the issues are solved now :)

**Comment by tfesenbecker** [comment]
Seems to work!

**Comment by eileen-kuehn** [comment]
Great! If you experience any other issues, please feel free to open more tickets :)
