### ISSUE TITLE
Number of cores in used_resources assigned to CPU efficiency?

### ISSUE THREAD

**Issue by tfesenbecker** [MatterMiners/lapis#48]
I am rather confused by 
https://github.com/MatterMiners/lapis/blob/f6523bca3adb0caba537d67700881bcda3ceaee1/lapis/job_io/htcondor.py#L50-L57 
This seems to assign the number of cores the job actually used to  `RemoteSysCpu + RemoteUserCpu/Walltime`. This does not make any sense to me and is strange considering units. 
Did you mean to assign this to the jobs CPU efficiency `(RemoteSysCpu + RemoteUserCpu)/Walltime`? And in this case: why?
Furthermore: 
https://github.com/MatterMiners/lapis/blob/f6523bca3adb0caba537d67700881bcda3ceaee1/lapis/job_io/htcondor.py#L56 references `unit_conversion_mapping["DiskUsage_Raw"] = 9.765625e-07` what further confuses my understanding of what is happening.
Or am I completely mistaken?

**Comment by maxfischer2781** [comment]
The first one looks like a typo indeed. It should be ``(RemoteSysCpu + RemoteUserCpu) / Walltime`` to get the CPU efficiency. HTCondor splits the CPU time into kernel ("system") and user space, similar to ``/usr/bin/time``.

**Comment by tfesenbecker** [comment]
But still: why do you assign  the CPU efficiency to  `used_resources["cores"]` and not to the number of cores used by the job as it is implied by the resources name mapping? 
https://github.com/MatterMiners/lapis/blob/f6523bca3adb0caba537d67700881bcda3ceaee1/lapis/job_io/htcondor.py#L15-L18

**Comment by eileen-kuehn** [comment]
@tfesenbecker, I distinguish between internally used names and names specified from external tools such as HTCondor, or the workload archive.

For internal names I wanted something that everybody can understand very well (and fast).

# Internal Keys

## Resources: 

* `cores`,
* `memory`, 
* `disk`, and 
* `walltime`.

You could also consider `gpu` as an extension here.

Further, I have some metadata, that is of general interest for simulation.

## Metadata

* `queuetime`.

# File formats

The input file formats have different headers giving information about the same underlying internal keys. Therefore, I introduced the name mapping to enable users for file formats that deviate from our exports.

From HTCondor exports there is no real information about the number of cores that are actually used. Therefore, we decided to use the CPU efficiency. In the export from @mschnepf there was this additional field `"Number of Allocated Processors"` that I just mapped to the `cores` but this is **overwritten** by the more accurate calculation to better determine how many resources are actually wasted.
