### ISSUE TITLE
Jobs can run without a drone being assigned

### ISSUE THREAD

**Issue by eileen-kuehn** [MatterMiners/lapis#55]
Apparently jobs can run although not being properly assigned to a drone. We should take care that this cannot happen.

See:

> This happens in the unit tests... Same with the fileprovider in 
> https://github.com/tfesenbecker/lapis/blob/53ebec5ea004e4f031a0f70102276fe0102d62e4/lapis/job.py#L96

_Originally posted by @tfesenbecker in https://github.com/MatterMiners/lapis/pull/53_

**Comment by maxfischer2781** [comment]
Do we know how this happens yet? Since jobs are supposed to be run by the Drones, I'm unsure how a job can run without a drone.

**Comment by tfesenbecker** [comment]
This only occurs in unit tests. There is a unit test that is supposed to test the functionality of the job only. 
https://github.com/MatterMiners/lapis/blob/5e10d37d054ff87da91010260ab8ab8da52614c0/lapis_tests/test_job.py#L28-L36
In this case no drone is passed.
If this unit test is to be kept there maybe should be an implementation of a DummyDrone like the DummyScheduler in other unit tests.
