### ISSUE TITLE
Unit standardisation

### ISSUE THREAD

**Issue by eileen-kuehn** [MatterMiners/lapis#58]
We should decide the standardisation of units through the simulation. We should further decide on the *i*, so either KiB or KB (no matter what if K or M or G or ...). Currently I think we use GB.

> Concerning the storage size, I recommend deciding on *one* data size unit and sticking to it. If we use Bytes then ``float`` is enough to represent up to 8 PiB precisely increasing with the prefix (e.g. 8 EiB for KiB base); Since there are no fractional Bytes, using ``int`` would allow for arbitrarily large *and* precise storage size even when using Bytes.

_Originally posted by @maxfischer2781 in https://github.com/MatterMiners/lapis/pull/53_

**Comment by maxfischer2781** [comment]
Using plain bytes has the least problems in standardisation (we do not need to decide on KiB versus KB etc.) and is always precise *when using ``int``*. However, it might degrade to ``float`` during naive computations, which is imprecise beyond 8PB.

**Comment by maxfischer2781** [comment]
After some testing, I strongly favour ``int`` in Bytes. The only issue is silent coercion, but that can be covered by type checkers easily.

In contrast, if we use ``float`` in GB we have no way whatsoever to check against accidentally using a different unit.
