### ISSUE TITLE
Distribution while supporting namespaces

### ISSUE THREAD

**Issue by eileen-kuehn** [MatterMiners/lapis#96]
# Motivation
I created the project [lapis.caching](https://github.com/MatterMiners/lapis.caching) as I want to make the caching extension from @tfesenbecker maintainable next to lapis. For this I am planning to use a namespace so that users can optionally install the caching extension.

# The issue
However, currently I was using [flit](https://flit.readthedocs.io/en/latest/) for distribution. Flit uses ``__init__.py`` to specify a ``version`` of a package. This keeps me from using the current implementation of namespaces as defined in [PEP-420](https://www.python.org/dev/peps/pep-0420/). This requires me to remove ``__init__.py`` while this is still required by flit. You. see the issue?
I could go with ``setup.py`` and setuptools instead, but this somehow feels like a retrograde step and I really hesitate doing this.

# A solution?
I was reading a bit through the internet and found a [summary on python packaging](https://stefanoborini.com/current-status-of-python-packaging/). It suggests going with [poetry](https://python-poetry.org). I now tend to try this out.

# Call for proposals ;)
@MatterMiners/matterminers: are there any thoughts on this from you guys? Should I just give it a try? Any other options to consider?

P.S.: This might mean if poetry works well, that we could use it for all our projects ;)

**Comment by maxfischer2781** [comment]
Just for reference, ``pip`` also works with ``.toml`` these days ([``pip`` reference](https://pip.pypa.io/en/stable/reference/pip/#build-system-interface) and [PEP 517](https://www.python.org/dev/peps/pep-0517/)). A bit less of a step back, but poetry is definitely more feature rich.

**Comment by eileen-kuehn** [comment]
> Just for reference, `pip` also works with `.toml` these days ([`pip` reference](https://pip.pypa.io/en/stable/reference/pip/#build-system-interface) and [PEP 517](https://www.python.org/dev/peps/pep-0517/)). A bit less of a step back, but poetry is definitely more feature rich.

And comes with a much bigger overhead of features we might not require? 
But so far those I checked look reasonable... also the dependency might be worth to give it a shot.

**Comment by maxfischer2781** [comment]
Reviving this, since matterminers/lapis.caching#13 requires `lapis` to be a proper namespace package to work properly. While the installed code works, this is basically a hack that confuses both package managers and dev tools (IDEs, linters, ...).

Working on the changes for a namespace packaging.
